name: CI

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm i

      - run: npm run build

      - run: npm run test